# Generated by Django 3.1.4 on 2021-08-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept', models.CharField(max_length=200)),
                ('DeptID', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.IntegerField(max_length=100)),
                ('EmpName', models.CharField(max_length=200)),
                ('Age', models.IntegerField(max_length=4)),
                ('Dept', models.CharField(max_length=200)),
            ],
        ),
    ]
