# Generated by Django 3.1.4 on 2021-08-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='DeptID',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='EmpID',
        ),
    ]
