# Generated by Django 3.1.4 on 2021-08-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210817_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='DeptID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='Age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='EmpID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
