# Generated by Django 3.1.4 on 2021-08-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210817_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='myapp_Departments',
        ),
        migrations.RenameModel(
            old_name='employees',
            new_name='myapp_employees',
        ),
    ]
