# Generated by Django 3.1.4 on 2021-08-18 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210817_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='Dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employees'),
        ),
    ]
